name: Tests
on: [push, pull_request]
jobs:
  lumen-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.3']
        phpunit-versions: ['7.0']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.3'
    services:
      mysql:
        image: mariadb:10.3.11
        env:
          MYSQL_DATABASE: test_database
          MYSQL_USER: admin
          MYSQL_PASSWORD: rootpass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.3'
      - name: Copy .env
        run: |
          php -r "file_exists('.env') || copy('.env.github', '.env');"   
      - name: Update Composer
        run: sudo composer self-update 1.10.15 --no-interaction
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: php clear config
        run: php artisan config:clear
      - name: PHP Artisan Key Generate
        run: php artisan key:generate
      - name: Verify MySQL connection
        run: |
          ping mysql -n 3
          echo ${{ job.services.mysql.ports['3306'] }}
          sudo apt-get install -y mysql-client
          mysql -hlocalhost -P${{ job.services.mysql.ports['3306'] }} -ucishe -pcishe -e "SHOW DATABASES"       
#       - name: PHP Artisan cache clear
#         run: php artisan key:generate
      - name: Install PHP dependencies
        run: php artisan cache:clear      
      - name: Database Migration
        run: php artisan migrate 
      - name: Database seed
        run: php artisan db:seed      
      - name: Update Composer
        run: sudo composer self-update 1.10.15 --no-interaction       
      - name: php artisan serve
        run: php artisan serve &
      - name: run tests
        run: vendor/bin/phpunit
