name: Tests
on: [push, pull_request]
jobs:
  lumen-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4']
        phpunit-versions: ['9.0']
#         phpunit-versions: ['7.0']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.4'
    services:
      mysqldb:
        image: mysql:5.7
#         container_name: php_alpine
        volumes:
            - dbdata:/var/lib/mysql/
        ports:
            - 3306:3306
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: test_database
#           MYSQL_USER: root
          MYSQL_PASSWORD: rootpass
          MYSQL_ROOT_PASSWORD: rootpass
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
      
        with:
          php-version: '7.3'
      - name: Verify MySQL connection from container 
        run: | 
          apt-get update &
          apt-get install -y mysql-client &
          mysql --host mysqldb -uroot -prootpass -e "SHOW DATABASES"  ||  mysql --host localhost -uroot -prootpass -e "SHOW DATABASES"   ||  mysql --host 127.0.0.1 -uroot -prootpass -e "SHOW DATABASES"      
      - name: Copy .env
        run: |
          mysql --host 127.0.0.1 -uroot -prootpass -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpass';"
          php -r "file_exists('.env') || copy('.env.github', '.env');" 
          cp .env.github .env
      - name: Update Composer
        run: sudo composer self-update 1.10.15 --no-interaction
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: php clear config
        run: php artisan config:clear
      - name: PHP Artisan Key Generate
        run: php artisan key:generate
      - name: test docker networks
        run: docker network ls
      - name: test docker containers 
        run: docker container ls -a
      - name: test docker containers details
        run: docker inspect $(sudo docker ps -aq)
      - name: Verify MySQL connection
        run: |
          ping mysql -n 3 || ping mariadb -n 3 || ping mysqldb -n 3 || echo "nothing working"
          echo ${{ job.services.mysql.ports['3306'] }} &
          sudo apt-get install -y mysql-client &
          mysql -hlocalhost -P${{ job.services.mysql.ports['3306'] }} -ucishe -pcishe -e "SHOW DATABASES"     & 
#       - name: PHP Artisan cache clear
#         run: php artisan key:generate
      - name: Install PHP dependencies
        run: php artisan cache:clear      
      - name: Database Migration
        run: php artisan migrate 
      - name: Database seed
        run: php artisan db:seed      
      - name: Update Composer
        run: sudo composer self-update 1.10.15 --no-interaction       
      - name: php artisan serve
        run: php artisan serve &
      - name: run tests
        env:
         DB_CONNECTION: mysql
         DB_DATABASE: test_database
         DB_USER: root
         DB_PASSWORD: rootpass
        run: |  
          ls -la
          cp .env.github .env
          php artisan config:clear
          php artisan key:generate
          php artisan migrate 
          php artisan db:seed
          vendor/bin/phpunit || composer test
